services:
  - type: web
    name: wa-pdf-bot
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: WA_TOKEN
        sync: false
      - key: WA_PHONE_ID
        sync: false
      - key: VERIFY_TOKEN
        sync: false
